apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastalert
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  project: default
  source:
    repoURL: 'https://github.com/kalaytan/elastalert-operator'
    targetRevision: HEAD
    path: deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: alert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
