apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alert

resources:
  - namespace.yaml
  - es.noah.domain_elastalerts.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
  - deployment.yaml